version: "3.8"
services:
  ### Vector model server (Ollama)
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    restart: unless-stopped

  ### Vector store (Qdrant)
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant:/qdrant/storage
    restart: unless-stopped

  ### FastAPI backend providing RAG APIs
  api:
    build:
      context: ./api
    container_name: rag_api
    env_file:
      - ./api/.env
    ports:
      - "8000:8000"
    depends_on:
      - ollama
      - qdrant
    restart: unless-stopped

  ### Front-end (e.g. Streamlit)
  web-ui:
    build:
      context: ./web_ui
    container_name: web_ui
    depends_on:
      - api
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://api:8000
    restart: unless-stopped

  ### Jupyter Notebook environment
  jupyter:
    build:
      context: ./notebooks
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=devtoken
    depends_on:
      - ollama
      - qdrant
    restart: unless-stopped

# 로컬 경로 마운트를 사용하므로 volumes 섹션이 필요 없음
