version: "3.8"
services:
  ### Vector model server (Ollama)
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  ### Vector store (Qdrant)
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  ### FastAPI backend providing RAG APIs
  api:
    build:
      context: ./api
    container_name: rag_api
    env_file:
      - ./api/.env
    ports:
      - "8000:8000"
    depends_on:
      - ollama
      - qdrant
    volumes:
      - ./api:/app
    restart: unless-stopped

  ### Front-end (e.g. Streamlit)
  web-ui:
    build:
      context: ./web_ui
    container_name: web_ui
    depends_on:
      - api
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://api:8000
    volumes:
      - ./web_ui:/app
    restart: unless-stopped

  ### Jupyter Notebook environment
  jupyter:
    image: jupyter/base-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=devtoken
    depends_on:
      - ollama
      - qdrant
    restart: unless-stopped

volumes:
  ollama_data: {}
  qdrant_data: {}
