services:
  ### Vector model server (Ollama)
  ollama:
    image: ollama/ollama:latest
    container_name: rnd_ollama
    ports:
      - "11435:11434"
    volumes:
      - ./ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "8G"
