services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11435:11434"
    volumes:
      - ./backend/ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
  rag-api:
    build:
      context: ./backend
    container_name: rag-api
    volumes:
      - ./backend:/app
      - ./backend/ollama:/root/.ollama
      - ./backend/models:/app/models  # HF 모델 저장소
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - ollama